name: deploy

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "10"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build and deploy
        run: gulp deploy
      
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@4.1.0
      #   with:
      #     branch: master # The branch the action should deploy to.
      #     folder: build # The folder the action should deploy.